// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8mwQ-BpKFwbp_Cnxp3UURxi7gU5bqa1w',
    appId: '1:943944922076:web:a506d4bd187f705f541519',
    messagingSenderId: '943944922076',
    projectId: 'educonnect-f790e',
    authDomain: 'educonnect-f790e.firebaseapp.com',
    storageBucket: 'educonnect-f790e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBby0_bX5O07oxF-e0-fNQGsQXRXXab9r0',
    appId: '1:943944922076:android:7f5656433d3044dc541519',
    messagingSenderId: '943944922076',
    projectId: 'educonnect-f790e',
    storageBucket: 'educonnect-f790e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqVl6kBvXpJ83YnGWCLOf8T3Gc-_7J68',
    appId: '1:943944922076:ios:6abbfbbe75e82a7a541519',
    messagingSenderId: '943944922076',
    projectId: 'educonnect-f790e',
    storageBucket: 'educonnect-f790e.firebasestorage.app',
    iosBundleId: 'com.example.educonnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqVl6kBvXpJ83YnGWCLOf8T3Gc-_7J68',
    appId: '1:943944922076:ios:6abbfbbe75e82a7a541519',
    messagingSenderId: '943944922076',
    projectId: 'educonnect-f790e',
    storageBucket: 'educonnect-f790e.firebasestorage.app',
    iosBundleId: 'com.example.educonnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8mwQ-BpKFwbp_Cnxp3UURxi7gU5bqa1w',
    appId: '1:943944922076:web:30409a02037b3a04541519',
    messagingSenderId: '943944922076',
    projectId: 'educonnect-f790e',
    authDomain: 'educonnect-f790e.firebaseapp.com',
    storageBucket: 'educonnect-f790e.firebasestorage.app',
  );
}
